// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZ8c1sAETjfF5T2d6999nmlNWOAXf9Vw',
    appId: '1:741316905013:web:e95d60c7c7a390756b897c',
    messagingSenderId: '741316905013',
    projectId: 'chatappbuild-8edbd',
    authDomain: 'chatappbuild-8edbd.firebaseapp.com',
    storageBucket: 'chatappbuild-8edbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsc3__lkHGB0uUv_-cqKPaehVHhdDMnaQ',
    appId: '1:741316905013:android:9f8b79c0f0ddee216b897c',
    messagingSenderId: '741316905013',
    projectId: 'chatappbuild-8edbd',
    storageBucket: 'chatappbuild-8edbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP9JmzjEXBlAsT50wADVKX2odF9xM15q8',
    appId: '1:741316905013:ios:ef102322e56131656b897c',
    messagingSenderId: '741316905013',
    projectId: 'chatappbuild-8edbd',
    storageBucket: 'chatappbuild-8edbd.appspot.com',
    iosBundleId: 'com.example.chatappbuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP9JmzjEXBlAsT50wADVKX2odF9xM15q8',
    appId: '1:741316905013:ios:ef102322e56131656b897c',
    messagingSenderId: '741316905013',
    projectId: 'chatappbuild-8edbd',
    storageBucket: 'chatappbuild-8edbd.appspot.com',
    iosBundleId: 'com.example.chatappbuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMZ8c1sAETjfF5T2d6999nmlNWOAXf9Vw',
    appId: '1:741316905013:web:bd5ef06f3ebf74a26b897c',
    messagingSenderId: '741316905013',
    projectId: 'chatappbuild-8edbd',
    authDomain: 'chatappbuild-8edbd.firebaseapp.com',
    storageBucket: 'chatappbuild-8edbd.appspot.com',
  );
}
